### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by monroemann** [kirillshevch/news_api#2]
@kirillshevch I am a volunteer at a not-for-profit (breakdiving.io).

Am I correct in understanding that this gem will allow us to display news from around the world in a news feed on our site?  

If so, from which sources?  Where does it get the news headlines?  

And how would we actually display the items?  Via a  .each do loop?

Thanks!
-Monroe

**Comment by kirillshevch** [comment]
Hi @monroemann

I'm not affiliated with newsapi.org, It's just unofficial API wrapper.
But in any case, you can find the answer on the official website:

Sources: https://newsapi.org/sources
